### ISSUE TITLE
avl.lisp

### ISSUE THREAD

**Issue by lispm** [langthom/data-structures#3]
size of the tree is not updated (increased or decreased).  + and - have no side effect. use INCF and DECF instead.

(let () (progn ...)) is usually just (let () ....)

(progn (setf a b) (setf c d))   is just (setf a b c d)

**Comment by langthom** [comment]
I fixed this now, thank you for your help! I really didn't know the last two points ...
I also fixed the increasing and decreasing of the tree size, was kinda silly from my side :)
